{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b4904d71",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import glob\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import xarray as xr\n",
    "\n",
    "import cartopy.crs as ccrs\n",
    "import cartopy.feature as cf\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "56285e05",
   "metadata": {},
   "outputs": [],
   "source": [
    "dir_base = os.path.join('/','media','arturo','Arturo','Data', 'Brazil', 'MERGE_INPE')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d2f99867",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of files: 8750\n"
     ]
    }
   ],
   "source": [
    "file_list = glob.glob(os.path.join(dir_base, '2024', 'raw', '*.grib2'))\n",
    "file_list = sorted(file_list)\n",
    "file_len = len(file_list)\n",
    "print(f'Number of files: {file_len}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "66443847",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of dates: 8784\n"
     ]
    }
   ],
   "source": [
    "dates_all = pd.date_range(\n",
    "        start=f\"2024-01-01 00:00:00\",\n",
    "        end=f\"2024-12-31 23:59:00\",\n",
    "        freq=\"1h\"\n",
    "        ).strftime(\"%Y-%m-%d %H\").tolist()\n",
    "print(f'Number of dates: {len(dates_all)}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e17b38df",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024042404.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024042404.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024042404.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024042404.grib2.5b7b6.idx'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FIle not found: MERGE_CPTEC_2024042404.grib2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024091912.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024091912.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024091912.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024091912.grib2.5b7b6.idx'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FIle not found: MERGE_CPTEC_2024091912.grib2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100710.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100710.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100710.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100710.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100715.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100715.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100715.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100715.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100716.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100716.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100716.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100716.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100717.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100717.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100717.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100717.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100718.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100718.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100718.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100718.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100719.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100719.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100719.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100719.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100720.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100720.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100720.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100720.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100721.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100721.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100721.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024100721.grib2.5b7b6.idx'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FIle not found: MERGE_CPTEC_2024100710.grib2\n",
      "FIle not found: MERGE_CPTEC_2024100715.grib2\n",
      "FIle not found: MERGE_CPTEC_2024100716.grib2\n",
      "FIle not found: MERGE_CPTEC_2024100717.grib2\n",
      "FIle not found: MERGE_CPTEC_2024100718.grib2\n",
      "FIle not found: MERGE_CPTEC_2024100719.grib2\n",
      "FIle not found: MERGE_CPTEC_2024100720.grib2\n",
      "FIle not found: MERGE_CPTEC_2024100721.grib2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111702.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111702.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111702.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111702.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111706.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111706.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111706.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111706.grib2.5b7b6.idx'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FIle not found: MERGE_CPTEC_2024111702.grib2\n",
      "FIle not found: MERGE_CPTEC_2024111706.grib2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111800.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111800.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111800.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111800.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111802.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111802.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111802.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024111802.grib2.5b7b6.idx'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FIle not found: MERGE_CPTEC_2024111800.grib2\n",
      "FIle not found: MERGE_CPTEC_2024111802.grib2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121504.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121504.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121504.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121504.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121505.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121505.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121505.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121505.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121506.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121506.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121506.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121506.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121507.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121507.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121507.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121507.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121508.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121508.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121508.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121508.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121509.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121509.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121509.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121509.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121510.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121510.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121510.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121510.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121511.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121511.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121511.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121511.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121512.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121512.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121512.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121512.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121513.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121513.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121513.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121513.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121514.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121514.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121514.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121514.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121515.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121515.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121515.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121515.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121516.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121516.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121516.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121516.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121517.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121517.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121517.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121517.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121518.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121518.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121518.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121518.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121519.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121519.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121519.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121519.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121520.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121520.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121520.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121520.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121521.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121521.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121521.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121521.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121522.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121522.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121522.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121522.grib2.5b7b6.idx'\n",
      "Can't create file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121523.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 539, in from_indexpath_or_filestream\n",
      "    self = cls.from_fieldset(filestream, index_keys, computed_keys)\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 379, in from_fieldset\n",
      "    return cls.from_fieldset_and_iteritems(fieldset, iteritems, index_keys, computed_keys)\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 392, in from_fieldset_and_iteritems\n",
      "    for field_id, raw_field in iteritems:\n",
      "                               ^^^^^^^^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 292, in __iter__\n",
      "    for message in self.itervalues():\n",
      "                   ~~~~~~~~~~~~~~~^^\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 268, in itervalues\n",
      "    with open(self.filestream.path, \"rb\") as file:\n",
      "         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121523.grib2'\n",
      "Can't read index file '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121523.grib2.5b7b6.idx'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/arturo/anaconda3/envs/AXE/lib/python3.13/site-packages/cfgrib/messages.py\", line 548, in from_indexpath_or_filestream\n",
      "    index_mtime = os.path.getmtime(indexpath)\n",
      "  File \"<frozen genericpath>\", line 91, in getmtime\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/media/arturo/Arturo/Data/Brazil/MERGE_INPE/2024/raw/MERGE_CPTEC_2024121523.grib2.5b7b6.idx'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FIle not found: MERGE_CPTEC_2024121504.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121505.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121506.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121507.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121508.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121509.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121510.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121511.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121512.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121513.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121514.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121515.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121516.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121517.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121518.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121519.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121520.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121521.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121522.grib2\n",
      "FIle not found: MERGE_CPTEC_2024121523.grib2\n"
     ]
    }
   ],
   "source": [
    "PRE = None\n",
    "for nn in range(len(dates_all)):\n",
    "    time_ref = pd.Timestamp(dates_all[nn]).strftime('%Y%m%d%H')\n",
    "\n",
    "    try:\n",
    "        tmp = xr.open_dataset(os.path.join(dir_base,'2024','raw',f'MERGE_CPTEC_{time_ref}.grib2'))\n",
    "        if PRE is None:\n",
    "            lat = tmp.latitude.values\n",
    "            lon = tmp.longitude.values\n",
    "            PRE = np.zeros((len(dates_all), len(lat), len(lon)))\n",
    "        PRE[nn,:,:] = tmp.rdp.values\n",
    "\n",
    "    except:\n",
    "        print(f'FIle not found: {f'MERGE_CPTEC_{time_ref}.grib2'}')\n",
    "        PRE[nn,:,:] = np.nan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "d71972be",
   "metadata": {},
   "outputs": [],
   "source": [
    "lat = tmp.latitude.values\n",
    "lon = tmp.longitude.values\n",
    "lon2d, lat2d = np.meshgrid(lon, lat)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1c097f72",
   "metadata": {},
   "outputs": [],
   "source": [
    "PRE_xr = xr.Dataset(data_vars={\"PRE\": ((\"time\",\"lat\",\"lon\"), PRE)},\n",
    "                    coords={'time': pd.to_datetime(dates_all), 'lat': lat, 'lon': lon-360},\n",
    "                    attrs=dict(description='MERGE CPTEC hourly precipitation for 2024',))\n",
    "\n",
    "PRE_xr.PRE.attrs[\"units\"] = \"mm/h\"\n",
    "PRE_xr.PRE.attrs[\"long_name\"] = \"precipitation\"\n",
    "PRE_xr.PRE.attrs[\"origname\"] = \"precipitation\"\n",
    "\n",
    "PRE_xr.lat.attrs[\"units\"] = \"degrees_north\"\n",
    "PRE_xr.lat.attrs[\"long_name\"] = \"Latitude\"\n",
    "\n",
    "PRE_xr.lon.attrs[\"units\"] = \"degrees_east\"\n",
    "PRE_xr.lon.attrs[\"long_name\"] = \"Longitude\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "fd009ce2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Start time: 01/01/2024\n",
      "End time: 31/12/2024\n"
     ]
    }
   ],
   "source": [
    "yy_s = pd.to_datetime(dates_all[0]).year\n",
    "mm_s = str(pd.to_datetime(dates_all[0]).month).zfill(2)\n",
    "dd_s = str(pd.to_datetime(dates_all[0]).day).zfill(2)\n",
    "\n",
    "yy_e = pd.to_datetime(dates_all[-1]).year\n",
    "mm_e = str(pd.to_datetime(dates_all[-1]).month).zfill(2)\n",
    "dd_e = str(pd.to_datetime(dates_all[-1]).day).zfill(2)\n",
    "\n",
    "print(f'Start time: {dd_s}/{mm_s}/{yy_s}')\n",
    "print(f'End time: {dd_e}/{mm_e}/{yy_e}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "47c8fb50",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div><svg style=\"position: absolute; width: 0; height: 0; overflow: hidden\">\n",
       "<defs>\n",
       "<symbol id=\"icon-database\" viewBox=\"0 0 32 32\">\n",
       "<path d=\"M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z\"></path>\n",
       "<path d=\"M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z\"></path>\n",
       "<path d=\"M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z\"></path>\n",
       "</symbol>\n",
       "<symbol id=\"icon-file-text2\" viewBox=\"0 0 32 32\">\n",
       "<path d=\"M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z\"></path>\n",
       "<path d=\"M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z\"></path>\n",
       "<path d=\"M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z\"></path>\n",
       "<path d=\"M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z\"></path>\n",
       "</symbol>\n",
       "</defs>\n",
       "</svg>\n",
       "<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.\n",
       " *\n",
       " */\n",
       "\n",
       ":root {\n",
       "  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));\n",
       "  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));\n",
       "  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));\n",
       "  --xr-border-color: var(--jp-border-color2, #e0e0e0);\n",
       "  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);\n",
       "  --xr-background-color: var(--jp-layout-color0, white);\n",
       "  --xr-background-color-row-even: var(--jp-layout-color1, white);\n",
       "  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);\n",
       "}\n",
       "\n",
       "html[theme=\"dark\"],\n",
       "html[data-theme=\"dark\"],\n",
       "body[data-theme=\"dark\"],\n",
       "body.vscode-dark {\n",
       "  --xr-font-color0: rgba(255, 255, 255, 1);\n",
       "  --xr-font-color2: rgba(255, 255, 255, 0.54);\n",
       "  --xr-font-color3: rgba(255, 255, 255, 0.38);\n",
       "  --xr-border-color: #1f1f1f;\n",
       "  --xr-disabled-color: #515151;\n",
       "  --xr-background-color: #111111;\n",
       "  --xr-background-color-row-even: #111111;\n",
       "  --xr-background-color-row-odd: #313131;\n",
       "}\n",
       "\n",
       ".xr-wrap {\n",
       "  display: block !important;\n",
       "  min-width: 300px;\n",
       "  max-width: 700px;\n",
       "}\n",
       "\n",
       ".xr-text-repr-fallback {\n",
       "  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */\n",
       "  display: none;\n",
       "}\n",
       "\n",
       ".xr-header {\n",
       "  padding-top: 6px;\n",
       "  padding-bottom: 6px;\n",
       "  margin-bottom: 4px;\n",
       "  border-bottom: solid 1px var(--xr-border-color);\n",
       "}\n",
       "\n",
       ".xr-header > div,\n",
       ".xr-header > ul {\n",
       "  display: inline;\n",
       "  margin-top: 0;\n",
       "  margin-bottom: 0;\n",
       "}\n",
       "\n",
       ".xr-obj-type,\n",
       ".xr-array-name {\n",
       "  margin-left: 2px;\n",
       "  margin-right: 10px;\n",
       "}\n",
       "\n",
       ".xr-obj-type {\n",
       "  color: var(--xr-font-color2);\n",
       "}\n",
       "\n",
       ".xr-sections {\n",
       "  padding-left: 0 !important;\n",
       "  display: grid;\n",
       "  grid-template-columns: 150px auto auto 1fr 0 20px 0 20px;\n",
       "}\n",
       "\n",
       ".xr-section-item {\n",
       "  display: contents;\n",
       "}\n",
       "\n",
       ".xr-section-item input {\n",
       "  display: inline-block;\n",
       "  opacity: 0;\n",
       "  height: 0;\n",
       "}\n",
       "\n",
       ".xr-section-item input + label {\n",
       "  color: var(--xr-disabled-color);\n",
       "}\n",
       "\n",
       ".xr-section-item input:enabled + label {\n",
       "  cursor: pointer;\n",
       "  color: var(--xr-font-color2);\n",
       "}\n",
       "\n",
       ".xr-section-item input:focus + label {\n",
       "  border: 2px solid var(--xr-font-color0);\n",
       "}\n",
       "\n",
       ".xr-section-item input:enabled + label:hover {\n",
       "  color: var(--xr-font-color0);\n",
       "}\n",
       "\n",
       ".xr-section-summary {\n",
       "  grid-column: 1;\n",
       "  color: var(--xr-font-color2);\n",
       "  font-weight: 500;\n",
       "}\n",
       "\n",
       ".xr-section-summary > span {\n",
       "  display: inline-block;\n",
       "  padding-left: 0.5em;\n",
       "}\n",
       "\n",
       ".xr-section-summary-in:disabled + label {\n",
       "  color: var(--xr-font-color2);\n",
       "}\n",
       "\n",
       ".xr-section-summary-in + label:before {\n",
       "  display: inline-block;\n",
       "  content: \"►\";\n",
       "  font-size: 11px;\n",
       "  width: 15px;\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       ".xr-section-summary-in:disabled + label:before {\n",
       "  color: var(--xr-disabled-color);\n",
       "}\n",
       "\n",
       ".xr-section-summary-in:checked + label:before {\n",
       "  content: \"▼\";\n",
       "}\n",
       "\n",
       ".xr-section-summary-in:checked + label > span {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       ".xr-section-summary,\n",
       ".xr-section-inline-details {\n",
       "  padding-top: 4px;\n",
       "  padding-bottom: 4px;\n",
       "}\n",
       "\n",
       ".xr-section-inline-details {\n",
       "  grid-column: 2 / -1;\n",
       "}\n",
       "\n",
       ".xr-section-details {\n",
       "  display: none;\n",
       "  grid-column: 1 / -1;\n",
       "  margin-bottom: 5px;\n",
       "}\n",
       "\n",
       ".xr-section-summary-in:checked ~ .xr-section-details {\n",
       "  display: contents;\n",
       "}\n",
       "\n",
       ".xr-array-wrap {\n",
       "  grid-column: 1 / -1;\n",
       "  display: grid;\n",
       "  grid-template-columns: 20px auto;\n",
       "}\n",
       "\n",
       ".xr-array-wrap > label {\n",
       "  grid-column: 1;\n",
       "  vertical-align: top;\n",
       "}\n",
       "\n",
       ".xr-preview {\n",
       "  color: var(--xr-font-color3);\n",
       "}\n",
       "\n",
       ".xr-array-preview,\n",
       ".xr-array-data {\n",
       "  padding: 0 5px !important;\n",
       "  grid-column: 2;\n",
       "}\n",
       "\n",
       ".xr-array-data,\n",
       ".xr-array-in:checked ~ .xr-array-preview {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       ".xr-array-in:checked ~ .xr-array-data,\n",
       ".xr-array-preview {\n",
       "  display: inline-block;\n",
       "}\n",
       "\n",
       ".xr-dim-list {\n",
       "  display: inline-block !important;\n",
       "  list-style: none;\n",
       "  padding: 0 !important;\n",
       "  margin: 0;\n",
       "}\n",
       "\n",
       ".xr-dim-list li {\n",
       "  display: inline-block;\n",
       "  padding: 0;\n",
       "  margin: 0;\n",
       "}\n",
       "\n",
       ".xr-dim-list:before {\n",
       "  content: \"(\";\n",
       "}\n",
       "\n",
       ".xr-dim-list:after {\n",
       "  content: \")\";\n",
       "}\n",
       "\n",
       ".xr-dim-list li:not(:last-child):after {\n",
       "  content: \",\";\n",
       "  padding-right: 5px;\n",
       "}\n",
       "\n",
       ".xr-has-index {\n",
       "  font-weight: bold;\n",
       "}\n",
       "\n",
       ".xr-var-list,\n",
       ".xr-var-item {\n",
       "  display: contents;\n",
       "}\n",
       "\n",
       ".xr-var-item > div,\n",
       ".xr-var-item label,\n",
       ".xr-var-item > .xr-var-name span {\n",
       "  background-color: var(--xr-background-color-row-even);\n",
       "  margin-bottom: 0;\n",
       "}\n",
       "\n",
       ".xr-var-item > .xr-var-name:hover span {\n",
       "  padding-right: 5px;\n",
       "}\n",
       "\n",
       ".xr-var-list > li:nth-child(odd) > div,\n",
       ".xr-var-list > li:nth-child(odd) > label,\n",
       ".xr-var-list > li:nth-child(odd) > .xr-var-name span {\n",
       "  background-color: var(--xr-background-color-row-odd);\n",
       "}\n",
       "\n",
       ".xr-var-name {\n",
       "  grid-column: 1;\n",
       "}\n",
       "\n",
       ".xr-var-dims {\n",
       "  grid-column: 2;\n",
       "}\n",
       "\n",
       ".xr-var-dtype {\n",
       "  grid-column: 3;\n",
       "  text-align: right;\n",
       "  color: var(--xr-font-color2);\n",
       "}\n",
       "\n",
       ".xr-var-preview {\n",
       "  grid-column: 4;\n",
       "}\n",
       "\n",
       ".xr-index-preview {\n",
       "  grid-column: 2 / 5;\n",
       "  color: var(--xr-font-color2);\n",
       "}\n",
       "\n",
       ".xr-var-name,\n",
       ".xr-var-dims,\n",
       ".xr-var-dtype,\n",
       ".xr-preview,\n",
       ".xr-attrs dt {\n",
       "  white-space: nowrap;\n",
       "  overflow: hidden;\n",
       "  text-overflow: ellipsis;\n",
       "  padding-right: 10px;\n",
       "}\n",
       "\n",
       ".xr-var-name:hover,\n",
       ".xr-var-dims:hover,\n",
       ".xr-var-dtype:hover,\n",
       ".xr-attrs dt:hover {\n",
       "  overflow: visible;\n",
       "  width: auto;\n",
       "  z-index: 1;\n",
       "}\n",
       "\n",
       ".xr-var-attrs,\n",
       ".xr-var-data,\n",
       ".xr-index-data {\n",
       "  display: none;\n",
       "  background-color: var(--xr-background-color) !important;\n",
       "  padding-bottom: 5px !important;\n",
       "}\n",
       "\n",
       ".xr-var-attrs-in:checked ~ .xr-var-attrs,\n",
       ".xr-var-data-in:checked ~ .xr-var-data,\n",
       ".xr-index-data-in:checked ~ .xr-index-data {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       ".xr-var-data > table {\n",
       "  float: right;\n",
       "}\n",
       "\n",
       ".xr-var-name span,\n",
       ".xr-var-data,\n",
       ".xr-index-name div,\n",
       ".xr-index-data,\n",
       ".xr-attrs {\n",
       "  padding-left: 25px !important;\n",
       "}\n",
       "\n",
       ".xr-attrs,\n",
       ".xr-var-attrs,\n",
       ".xr-var-data,\n",
       ".xr-index-data {\n",
       "  grid-column: 1 / -1;\n",
       "}\n",
       "\n",
       "dl.xr-attrs {\n",
       "  padding: 0;\n",
       "  margin: 0;\n",
       "  display: grid;\n",
       "  grid-template-columns: 125px auto;\n",
       "}\n",
       "\n",
       ".xr-attrs dt,\n",
       ".xr-attrs dd {\n",
       "  padding: 0;\n",
       "  margin: 0;\n",
       "  float: left;\n",
       "  padding-right: 10px;\n",
       "  width: auto;\n",
       "}\n",
       "\n",
       ".xr-attrs dt {\n",
       "  font-weight: normal;\n",
       "  grid-column: 1;\n",
       "}\n",
       "\n",
       ".xr-attrs dt:hover span {\n",
       "  display: inline-block;\n",
       "  background: var(--xr-background-color);\n",
       "  padding-right: 10px;\n",
       "}\n",
       "\n",
       ".xr-attrs dd {\n",
       "  grid-column: 2;\n",
       "  white-space: pre-wrap;\n",
       "  word-break: break-all;\n",
       "}\n",
       "\n",
       ".xr-icon-database,\n",
       ".xr-icon-file-text2,\n",
       ".xr-no-icon {\n",
       "  display: inline-block;\n",
       "  vertical-align: middle;\n",
       "  width: 1em;\n",
       "  height: 1.5em !important;\n",
       "  stroke-width: 0;\n",
       "  stroke: currentColor;\n",
       "  fill: currentColor;\n",
       "}\n",
       "</style><pre class='xr-text-repr-fallback'>&lt;xarray.Dataset&gt; Size: 24GB\n",
       "Dimensions:  (time: 8784, lat: 701, lon: 493)\n",
       "Coordinates:\n",
       "  * time     (time) datetime64[ns] 70kB 2024-01-01 ... 2024-12-31T23:00:00\n",
       "  * lat      (lat) float64 6kB -56.95 -56.85 -56.75 -56.65 ... 12.85 12.95 13.05\n",
       "  * lon      (lon) float64 4kB -82.15 -82.05 -81.95 ... -33.15 -33.05 -32.95\n",
       "Data variables:\n",
       "    PRE      (time, lat, lon) float64 24GB 0.2812 0.1406 0.1562 ... 0.0 0.0 0.0\n",
       "Attributes:\n",
       "    description:  MERGE CPTEC hourly precipitation for 2024</pre><div class='xr-wrap' style='display:none'><div class='xr-header'><div class='xr-obj-type'>xarray.Dataset</div></div><ul class='xr-sections'><li class='xr-section-item'><input id='section-0c193d93-8251-4908-832f-e2a1350da863' class='xr-section-summary-in' type='checkbox' disabled ><label for='section-0c193d93-8251-4908-832f-e2a1350da863' class='xr-section-summary'  title='Expand/collapse section'>Dimensions:</label><div class='xr-section-inline-details'><ul class='xr-dim-list'><li><span class='xr-has-index'>time</span>: 8784</li><li><span class='xr-has-index'>lat</span>: 701</li><li><span class='xr-has-index'>lon</span>: 493</li></ul></div><div class='xr-section-details'></div></li><li class='xr-section-item'><input id='section-2ca6c6d0-b1fd-4ec8-9e34-985de68468d4' class='xr-section-summary-in' type='checkbox'  checked><label for='section-2ca6c6d0-b1fd-4ec8-9e34-985de68468d4' class='xr-section-summary' >Coordinates: <span>(3)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>time</span></div><div class='xr-var-dims'>(time)</div><div class='xr-var-dtype'>datetime64[ns]</div><div class='xr-var-preview xr-preview'>2024-01-01 ... 2024-12-31T23:00:00</div><input id='attrs-9e6cca50-fc86-4055-a2ec-6e8c0f7341c6' class='xr-var-attrs-in' type='checkbox' disabled><label for='attrs-9e6cca50-fc86-4055-a2ec-6e8c0f7341c6' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-b7300425-6332-4062-8ddd-36285c9d59ef' class='xr-var-data-in' type='checkbox'><label for='data-b7300425-6332-4062-8ddd-36285c9d59ef' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'></dl></div><div class='xr-var-data'><pre>array([&#x27;2024-01-01T00:00:00.000000000&#x27;, &#x27;2024-01-01T01:00:00.000000000&#x27;,\n",
       "       &#x27;2024-01-01T02:00:00.000000000&#x27;, ..., &#x27;2024-12-31T21:00:00.000000000&#x27;,\n",
       "       &#x27;2024-12-31T22:00:00.000000000&#x27;, &#x27;2024-12-31T23:00:00.000000000&#x27;],\n",
       "      shape=(8784,), dtype=&#x27;datetime64[ns]&#x27;)</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>lat</span></div><div class='xr-var-dims'>(lat)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>-56.95 -56.85 ... 12.95 13.05</div><input id='attrs-47829ad1-9a4e-4ecd-9b12-ff95d49c536d' class='xr-var-attrs-in' type='checkbox' ><label for='attrs-47829ad1-9a4e-4ecd-9b12-ff95d49c536d' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-137031d1-756d-47d9-a4f4-430ac4fed933' class='xr-var-data-in' type='checkbox'><label for='data-137031d1-756d-47d9-a4f4-430ac4fed933' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'><dt><span>units :</span></dt><dd>degrees_north</dd><dt><span>long_name :</span></dt><dd>Latitude</dd></dl></div><div class='xr-var-data'><pre>array([-56.95, -56.85, -56.75, ...,  12.85,  12.95,  13.05], shape=(701,))</pre></div></li><li class='xr-var-item'><div class='xr-var-name'><span class='xr-has-index'>lon</span></div><div class='xr-var-dims'>(lon)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>-82.15 -82.05 ... -33.05 -32.95</div><input id='attrs-4b629f2c-e41e-44cb-bc41-f09a894a03d3' class='xr-var-attrs-in' type='checkbox' ><label for='attrs-4b629f2c-e41e-44cb-bc41-f09a894a03d3' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-38ae8670-962b-4d0d-93e0-38c7ae6d18d0' class='xr-var-data-in' type='checkbox'><label for='data-38ae8670-962b-4d0d-93e0-38c7ae6d18d0' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'><dt><span>units :</span></dt><dd>degrees_east</dd><dt><span>long_name :</span></dt><dd>Longitude</dd></dl></div><div class='xr-var-data'><pre>array([-82.15, -82.05, -81.95, ..., -33.15, -33.05, -32.95], shape=(493,))</pre></div></li></ul></div></li><li class='xr-section-item'><input id='section-996fe29e-aa5c-4eef-a330-20241ac7a4d8' class='xr-section-summary-in' type='checkbox'  checked><label for='section-996fe29e-aa5c-4eef-a330-20241ac7a4d8' class='xr-section-summary' >Data variables: <span>(1)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-var-name'><span>PRE</span></div><div class='xr-var-dims'>(time, lat, lon)</div><div class='xr-var-dtype'>float64</div><div class='xr-var-preview xr-preview'>0.2812 0.1406 0.1562 ... 0.0 0.0</div><input id='attrs-8051aff8-adae-43b4-a01b-bc2674617660' class='xr-var-attrs-in' type='checkbox' ><label for='attrs-8051aff8-adae-43b4-a01b-bc2674617660' title='Show/Hide attributes'><svg class='icon xr-icon-file-text2'><use xlink:href='#icon-file-text2'></use></svg></label><input id='data-f510f3b3-4c3c-48e3-96e3-540a5c928b2b' class='xr-var-data-in' type='checkbox'><label for='data-f510f3b3-4c3c-48e3-96e3-540a5c928b2b' title='Show/Hide data repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-var-attrs'><dl class='xr-attrs'><dt><span>units :</span></dt><dd>mm/h</dd><dt><span>long_name :</span></dt><dd>precipitation</dd><dt><span>origname :</span></dt><dd>precipitation</dd></dl></div><div class='xr-var-data'><pre>array([[[0.28125  , 0.140625 , 0.15625  , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.21875  , 0.140625 , 0.140625 , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.203125 , 0.109375 , 0.09375  , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        ...,\n",
       "        [0.359375 , 0.578125 , 0.5      , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.421875 , 0.4375   , 0.46875  , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.484375 , 0.4375   , 0.40625  , ..., 0.       , 0.       ,\n",
       "         0.       ]],\n",
       "\n",
       "       [[1.3125   , 1.25     , 0.890625 , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [2.0625   , 1.78125  , 1.625    , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [2.046875 , 2.109375 , 2.09375  , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "...\n",
       "        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,\n",
       "         0.       ]],\n",
       "\n",
       "       [[0.078125 , 0.       , 0.       , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.171875 , 0.       , 0.       , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.15625  , 0.09375  , 0.       , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        ...,\n",
       "        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,\n",
       "         0.       ],\n",
       "        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,\n",
       "         0.       ]]], shape=(8784, 701, 493))</pre></div></li></ul></div></li><li class='xr-section-item'><input id='section-3cb0a9b6-759f-4322-8632-9bc687f8a355' class='xr-section-summary-in' type='checkbox'  ><label for='section-3cb0a9b6-759f-4322-8632-9bc687f8a355' class='xr-section-summary' >Indexes: <span>(3)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><ul class='xr-var-list'><li class='xr-var-item'><div class='xr-index-name'><div>time</div></div><div class='xr-index-preview'>PandasIndex</div><input type='checkbox' disabled/><label></label><input id='index-c47d32cf-c2c6-4009-bd99-60484ef94eba' class='xr-index-data-in' type='checkbox'/><label for='index-c47d32cf-c2c6-4009-bd99-60484ef94eba' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(DatetimeIndex([&#x27;2024-01-01 00:00:00&#x27;, &#x27;2024-01-01 01:00:00&#x27;,\n",
       "               &#x27;2024-01-01 02:00:00&#x27;, &#x27;2024-01-01 03:00:00&#x27;,\n",
       "               &#x27;2024-01-01 04:00:00&#x27;, &#x27;2024-01-01 05:00:00&#x27;,\n",
       "               &#x27;2024-01-01 06:00:00&#x27;, &#x27;2024-01-01 07:00:00&#x27;,\n",
       "               &#x27;2024-01-01 08:00:00&#x27;, &#x27;2024-01-01 09:00:00&#x27;,\n",
       "               ...\n",
       "               &#x27;2024-12-31 14:00:00&#x27;, &#x27;2024-12-31 15:00:00&#x27;,\n",
       "               &#x27;2024-12-31 16:00:00&#x27;, &#x27;2024-12-31 17:00:00&#x27;,\n",
       "               &#x27;2024-12-31 18:00:00&#x27;, &#x27;2024-12-31 19:00:00&#x27;,\n",
       "               &#x27;2024-12-31 20:00:00&#x27;, &#x27;2024-12-31 21:00:00&#x27;,\n",
       "               &#x27;2024-12-31 22:00:00&#x27;, &#x27;2024-12-31 23:00:00&#x27;],\n",
       "              dtype=&#x27;datetime64[ns]&#x27;, name=&#x27;time&#x27;, length=8784, freq=None))</pre></div></li><li class='xr-var-item'><div class='xr-index-name'><div>lat</div></div><div class='xr-index-preview'>PandasIndex</div><input type='checkbox' disabled/><label></label><input id='index-bf9500f4-5986-4c96-9c83-24310f4fb260' class='xr-index-data-in' type='checkbox'/><label for='index-bf9500f4-5986-4c96-9c83-24310f4fb260' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(Index([             -56.95,              -56.85,              -56.75,\n",
       "                    -56.65,              -56.55, -56.449999999999996,\n",
       "       -56.349999999999994,  -56.24999999999999,  -56.14999999999999,\n",
       "        -56.04999999999999,\n",
       "       ...\n",
       "        12.150000000000512,  12.250000000000512,  12.350000000000511,\n",
       "         12.45000000000051,   12.55000000000051,   12.65000000000051,\n",
       "         12.75000000000051,   12.85000000000051,  12.950000000000509,\n",
       "                     13.05],\n",
       "      dtype=&#x27;float64&#x27;, name=&#x27;lat&#x27;, length=701))</pre></div></li><li class='xr-var-item'><div class='xr-index-name'><div>lon</div></div><div class='xr-index-preview'>PandasIndex</div><input type='checkbox' disabled/><label></label><input id='index-21941dc8-c615-4b79-8022-fe39773e1376' class='xr-index-data-in' type='checkbox'/><label for='index-21941dc8-c615-4b79-8022-fe39773e1376' title='Show/Hide index repr'><svg class='icon xr-icon-database'><use xlink:href='#icon-database'></use></svg></label><div class='xr-index-data'><pre>PandasIndex(Index([ -82.14999999999998,  -82.04999999999995,  -81.94999999999993,\n",
       "        -81.84999999999991,  -81.74999999999989,  -81.64999999999986,\n",
       "        -81.54999999999984,  -81.44999999999982,   -81.3499999999998,\n",
       "        -81.24999999999977,\n",
       "       ...\n",
       "       -33.849999999988995,  -33.74999999998897,  -33.64999999998895,\n",
       "        -33.54999999998893, -33.449999999988904,  -33.34999999998888,\n",
       "        -33.24999999998886, -33.149999999988836,  -33.04999999998881,\n",
       "        -32.94999999999999],\n",
       "      dtype=&#x27;float64&#x27;, name=&#x27;lon&#x27;, length=493))</pre></div></li></ul></div></li><li class='xr-section-item'><input id='section-acc7a5cb-0eee-49e5-a987-d07a4073a7b1' class='xr-section-summary-in' type='checkbox'  checked><label for='section-acc7a5cb-0eee-49e5-a987-d07a4073a7b1' class='xr-section-summary' >Attributes: <span>(1)</span></label><div class='xr-section-inline-details'></div><div class='xr-section-details'><dl class='xr-attrs'><dt><span>description :</span></dt><dd>MERGE CPTEC hourly precipitation for 2024</dd></dl></div></li></ul></div></div>"
      ],
      "text/plain": [
       "<xarray.Dataset> Size: 24GB\n",
       "Dimensions:  (time: 8784, lat: 701, lon: 493)\n",
       "Coordinates:\n",
       "  * time     (time) datetime64[ns] 70kB 2024-01-01 ... 2024-12-31T23:00:00\n",
       "  * lat      (lat) float64 6kB -56.95 -56.85 -56.75 -56.65 ... 12.85 12.95 13.05\n",
       "  * lon      (lon) float64 4kB -82.15 -82.05 -81.95 ... -33.15 -33.05 -32.95\n",
       "Data variables:\n",
       "    PRE      (time, lat, lon) float64 24GB 0.2812 0.1406 0.1562 ... 0.0 0.0 0.0\n",
       "Attributes:\n",
       "    description:  MERGE CPTEC hourly precipitation for 2024"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "PRE_xr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "b911772c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Export PRE data to /media/arturo/Arturo/Data/Brazil/MERGE_INPE/MERGE-INPE_SA_1h_2024_01_01_2024_12_31.nc\n"
     ]
    }
   ],
   "source": [
    "PRE_out = os.path.join(dir_base,f'MERGE-INPE_SA_1h_{yy_s}_{mm_s}_{dd_s}_{yy_e}_{mm_e}_{dd_e}.nc')\n",
    "print(f'Export PRE data to {PRE_out}')\n",
    "PRE_xr.to_netcdf(PRE_out)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "ee23c1ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "# proj = ccrs.PlateCarree()\n",
    "# fig = plt.figure(figsize=(4,4),dpi=300)\n",
    "# gs = gridspec.GridSpec(1,1)\n",
    "\n",
    "# #==================================================================================================\n",
    "# ax1 = plt.subplot(gs[0, 0], projection = proj)\n",
    "# # ax1.set_extent([-180, -30, -60, 70],crs=proj)\n",
    "# ax1.add_feature(cf.COASTLINE,linewidth=0.5, linestyle='-',edgecolor='k')\n",
    "# ax1.add_feature(cf.BORDERS, linewidth=0.5, linestyle='-', edgecolor='k')\n",
    "\n",
    "# a1 = ax1.pcolormesh(lon2d, lat2d, np.nanmean(PRE,axis=0))\n",
    "\n",
    "# gl = ax1.gridlines(crs=proj,draw_labels=True,linewidth=0.2,color='gray',alpha=0.5,linestyle='--')\n",
    "# gl.top_labels = False\n",
    "# gl.bottom_labels = True\n",
    "# gl.left_labels = True\n",
    "# gl.right_labels = False\n",
    "# gl.xlabel_style = {'size': 6, 'color': 'k'}\n",
    "# gl.ylabel_style = {'size': 6, 'color': 'k'}\n",
    "\n",
    "# cbar = plt.colorbar(a1, orientation='vertical', pad=0.05, fraction=0.049)\n",
    "# cbar.set_label('Precipitation (mm/h)', fontsize=6)\n",
    "# cbar.ax.tick_params(labelsize=6)\n",
    "\n",
    "# ax1.set_facecolor('white')\n",
    "# fig.patch.set_alpha(0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3e21fc93",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "AXE",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
